import { FormEvent, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowRight, BusFront, ChevronDown, Facebook, Instagram, Linkedin, MapPin, Youtube, Menu, ParkingCircle, Plus, Podcast, Music2, Sparkles, X } from "lucide-react";

const mainSite = "https://www.mtv-stuttgart.de/";
const membershipUrl = "https://www.mtv-stuttgart.de/service/jetzt-anmelden";
const sportCoursesUrl = "https://www.mtv-stuttgart.de/sportkurse";
const paraSportUrl = "https://www.mtv-stuttgart.de/para-sport";
const logo = "https://cdn.builder.io/api/v1/image/assets%2F97956c646ef740de89498cdc9738b7d6%2F706e7fda6e774224bf7097e38f689723?format=webp&width=800&height=1200";
const heroVideo = "https://cdn.builder.io/o/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fa7ff2f5ec42d47ffa8317c64a69b325c?alt=media&token=05a168a6-ea40-4b47-81ad-2c1138cbcd58&apiKey=ddb6ea6a9b7b4321af836c3cfcfa84c7";
const photos = [
  "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Ff4fec728abd04aa395551f9aef7f8219?format=webp&width=800&height=1200",
  "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fd0d11a4ba70b43c798963867097f4a6b?format=webp&width=800&height=1200",
  "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F8eee1df8dd8f46b9a38f3415eefeba67?format=webp&width=800&height=1200",
];
const offerings = [
  ["HYROX", "Kraft, Ausdauer und Teamgeist in einem intensiven Format.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F3b4e491ef60b4b4d8fd134a76793b207?format=webp&width=800&height=1200"],
  ["HIIT", "Kurze Intervalle, große Energie und ein Training, das dich mitnimmt.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fdbc3d7bc319f43c1bf822c1f41560053?format=webp&width=800&height=1200"],
  ["Schlingentraining", "Dein Körper wird zum Trainingsgerät – funktionell, vielseitig und für jedes Level.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fcf7e8bf3e6144331880afad676448b85?format=webp&width=800&height=1200"],
  ["Functional Fitness", "Bewegungen aus dem Alltag, neu gedacht für mehr Stabilität und Power.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fffb3992b5d354a6a92a9afe384bd11a4?format=webp&width=800&height=1200"],
  ["Pilates", "Bewusst bewegen, die Mitte stärken und neue Balance finden.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F83605d22678e4cc5ba22b84b32a74553?format=webp&width=800&height=1200"],
  ["Vinyasa Yoga", "Fließende Sequenzen, bewusster Atem und Zeit für dich.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F3062d34d32424ed48c288390a12b89a1?format=webp&width=800&height=1200"],
  ["Prä- & Postnatal Yoga", "Sanfte Bewegung und neue Kraft für die besondere Zeit vor und nach der Geburt.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Ff6f01c7973fd4f82ac17f185a3c5dbd4?format=webp&width=800&height=1200"],
  ["Kinderyoga", "Spielerisch zur Ruhe kommen, mutig bewegen und den eigenen Körper entdecken.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F8558c35bb4a14ae6a8d75642bcfc7348?format=webp&width=800&height=1200"],
] as const;
const levels = [
  ["3. OG", "3. Obergeschoss", "Büros & Seminarraum", "Austausch, Organisation und Weiterentwicklung für den Verein.", ["Workshops", "Fortbildungen", "externe Events"], "bg-ink"],
  ["2. OG", "2. Obergeschoss", "Sporthalle", "Viel Platz für Sport, Spiel und Training – inklusive Lü-System, Action Center und MultimotionCenter.", ["Vereinssport", "Schulsport", "Kindersport", "Vermietungen"], "bg-wood"],
  ["1. OG", "1. Obergeschoss", "Gymnastikhalle", "Ein vielseitiger Raum für Gymnastik, Kurse und gemeinsame Bewegung.", ["Kindersport", "Rehasport", "Yoga", "Pilates", "Tanzen"], "bg-coral"],
  ["EG", "Erdgeschoss", "Mikrostudio", "Kurze Wege, modernes Training und ein offener Treffpunkt für alle.", ["HYROX", "Functional Fitness", "Schlingentraining", "HIIT", "Athletiktraining", "Offenes Training"], "bg-sun"],
  ["UG", "Untergeschoss", "Umkleiden & Sitzungsraum", "Ankommen, umziehen und aktiv werden.", ["Umkleiden", "Sitzungsraum", "Technik"], "bg-sky"],
] as const;
const equipment = [
  ["Mikrostudio", "Kompakt. Intensiv. Persönlich.", "HYROX, Functional Fitness, HIIT, Schlingentraining, Athletiktraining und Fitnessboxen: fokussierte Formate für kleine Gruppen und offenes Training.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F6be5c17125bd4cfe855cf0951e8e9f55?format=webp&width=800&height=1200"],
  ["Lü-System", "Die Wand wird zum Spielfeld.", "Das Lü-System verwandelt die Sporthalle mit einer interaktiven Projektionsfläche, 3D-Kamera, Licht und Sound in ein digitales Spielfeld. Über 40 Apps und Programme verbinden Bewegung, Lernen und Spiel: Kinder und Erwachsene treffen Ziele, lösen Aufgaben und verbessern ihre koordinativen Fähigkeiten.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F396ca10405914e54ba4ffea71a52f394?format=webp&width=800&height=1200"],
  ["ActionCenter", "Bewegung als Abenteuer.", "Wenn sich die Wand öffnet, wird die Halle zur Abenteuerlandschaft: Kletternetz, Sprossenwand, Rutsche und viele weitere Elemente laden dazu ein, mutig loszulegen, gemeinsam zu entdecken und über sich hinauszuwachsen.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F295551c1782c47a791e8475db7505694?format=webp&width=800&height=1200"],
  ["MultiMotionCenter", "Parcours für jedes Level.", "Ein modulares Kletter- und Bewegungskonzept mit Kletterstangen, Leitern und Podeste, welche sich flexibel ausklappen lassen und mit Bänken, Kästen und Matten ergänzbar sind. So entsteht immer wieder eine neue Landschaft zum Klettern, Balancieren, Hangeln und gemeinsamen Wachsen.", "https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F8058a5f0141b4ad6b569bcfbbe308ba3?format=webp&width=800&height=1200"],
] as const;
const sponsors = ["Learnteq", "FinanzGefährte", "Friess + Merkle", "Dinkelacker-Schwaben Bräu", "BBBank eG", "PSD Bank RheinNeckarSaar eG"] as const;
const faqs = [
  {
    question: "Muss ich Mitglied im MTV Stuttgart sein, um den SPORT CUBE zu nutzen?",
    answer: <>Nein, du musst kein Mitglied sein.</>,
  },
  {
    question: "Was kostet eine Mitgliedschaft?",
    answer: <>Es gibt keine exklusive Mitgliedschaft für den SPORT CUBE. Je nach Kurs gibt es verschiedene Optionen, von Einmal-Drop-In über 10er-Karten bis hin zu 8er-Kursen. In der <a className="faq-answer-link" href={sportCoursesUrl} target="_blank" rel="noreferrer">Kursinfo</a> findest du unter Kursgebühren die jeweiligen Infos für deinen Kurs.</>,
  },
  {
    question: "Wie werde ich Mitglied?",
    answer: <>Über unsere <a className="faq-answer-link" href={membershipUrl} target="_blank" rel="noreferrer">Hauptwebsite</a> findest du mehr Infos.</>,
  },
  {
    question: "Gibt es ein Probetraining?",
    answer: <>Ja, wir haben ein spezielles Schnupperangebot für bestimmte Kurse im Mikrostudio und der Gymnastikhalle. Das hängt jedoch vom jeweiligen Kurs ab. Schau dafür am besten in den Kursinfos nach. Das Kursangebot findest du <a className="faq-answer-link" href={sportCoursesUrl} target="_blank" rel="noreferrer">hier</a>.</>,
  },
  {
    question: "Welche Kurse und Angebote gibt es im SPORT CUBE?",
    answer: <>Von Turnen &amp; Kindersport, HIIT &amp; HYROX, Reha- &amp; Para-Sport über Yoga &amp; Pilates sowie Tanzkurse haben wir ein breites Angebot an Kursen. Alle Kurse sowie Kursdetails findest du <a className="faq-answer-link" href={sportCoursesUrl} target="_blank" rel="noreferrer">hier</a>.</>,
  },
  {
    question: "Gibt es auch Angebote für Menschen mit Behinderung?",
    answer: <>Ja, der SPORT CUBE ist 100% barrierefrei und wird von unserer Parasport-Abteilung genutzt werden. Ansprechpartnerin hierfür ist Mandy Pierer. Mehr Infos findest du <a className="faq-answer-link" href={paraSportUrl} target="_blank" rel="noreferrer">hier</a>.</>,
  },
  {
    question: "Kann ich den SPORT CUBE auch für private Events nutzen?",
    answer: <>Ja, die Sporthalle und die Gymnastikhalle können für jegliche Events, Workshops, Kindergeburtstage, Junggesellenabschiede etc. gemietet werden. Im 3. Obergeschoss befindet sich des Weiteren ein Seminarraum, der ebenfalls extern vermietet werden kann.</>,
  },
  {
    question: "Gibt es für die internen Abteilungen Möglichkeiten die Räumlichkeiten zu nutzen?",
    answer: <>Ja, die Hallen und das Mikrostudio können außerhalb der Kurszeiträume nach Absprache genutzt werden. Zudem gibt es einen Sitzungsraum im Untergeschoss, der von den Abteilungen genutzt werden kann.</>,
  },
  {
    question: "Wann eröffnet der SPORT CUBE?",
    answer: <>Der SPORT CUBE wird voraussichtlich im Januar 2027 eröffnen.</>,
  },
  {
    question: "Wie kann ich den Baufortschritt verfolgen?",
    answer: <>Über Social Media, unseren MTV-Newsletter und regelmäßige Updates auf unserer <a className="faq-answer-link" href={mainSite} target="_blank" rel="noreferrer">Hauptwebsite</a>.</>,
  },
  {
    question: "Wie kann ich den SPORT CUBE unterstützen?",
    answer: <>Mit einer Spende auf unser Spendenkonto IBAN DE16 6004 0071 0553 6446 02 oder via PayPal. Zudem kannst du als Bausteinspender:in Teil des SPORT CUBE werden.</>,
  },
  {
    question: "Was ist die Bausteinaktion?",
    answer: <>Unterstützer:innen werden mit ihrem Namen dauerhaft auf der Spendenwand im Gebäude sichtbar gemacht. <a className="faq-answer-link" href="https://www.mtv-stuttgart.de/ueber-uns/sportpunkt#c1887" target="_blank" rel="noreferrer">Hier</a> geht's zur Bausteinaktion.</>,
  },
];

function Brand() { return <span className="flex items-center gap-3" aria-label="MTV Sport Cube"><span className="block h-12 w-12 overflow-hidden rounded-full"><img src={logo} alt="MTV Stuttgart" className="h-full w-full object-cover" /></span><span className="font-display text-base font-extrabold uppercase tracking-[-0.04em] text-white sm:text-xl">SPORT CUBE</span></span>; }
function scrollTo(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); }

export default function Index() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [activeOffer, setActiveOffer] = useState(0);
  const [openLevel, setOpenLevel] = useState(3);
  const [openFaq, setOpenFaq] = useState(0);
  const [sent, setSent] = useState(false);
  const navigate = (id: string) => { scrollTo(id); setMobileOpen(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  const current = levels[openLevel];

  return <div className="overflow-hidden bg-cream text-ink selection:bg-coral selection:text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-ink/95 text-white backdrop-blur-md"><div className="mx-auto flex h-[76px] max-w-[1440px] items-center justify-between px-5 lg:px-9"><button onClick={() => navigate("start")} aria-label="Zum Anfang"><Brand /></button><nav className="hidden items-center gap-7 text-[12px] font-bold uppercase tracking-[0.12em] lg:flex">{[["DER NEUBAU", "neubau"], ["ANGEBOT", "angebot"], ["AUSSTATTUNG", "ausstattung"], ["STANDORT", "standort"]].map(([label, id]) => <button key={id} className="nav-link" onClick={() => navigate(id)}>{label}</button>)}</nav><a href={membershipUrl} target="_blank" rel="noreferrer" className="hidden rounded-full bg-coral px-5 py-3 text-xs font-extrabold uppercase tracking-[0.1em] transition hover:bg-white hover:text-ink lg:block">MITGLIED WERDEN</a><button className="lg:hidden" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Menü öffnen">{mobileOpen ? <X /> : <Menu />}</button></div>{mobileOpen && <nav className="border-t border-white/10 bg-ink px-5 py-5 uppercase lg:hidden"><div className="flex flex-col gap-4 text-sm font-bold">{[["DER NEUBAU", "neubau"], ["ANGEBOT", "angebot"], ["AUSSTATTUNG", "ausstattung"], ["STANDORT", "standort"], ["MITGLIED WERDEN", "kontakt"]].map(([label, id]) => id === "kontakt" ? <a className="text-left" key={id} href={membershipUrl} target="_blank" rel="noreferrer">{label}</a> : <button className="text-left" key={id} onClick={() => navigate(id)}>{label}</button>)}</div></nav>}</header>
    <main id="start">
      <section className="relative flex min-h-[740px] items-end bg-ink pt-[76px] text-white md:min-h-[820px]"><video className="absolute inset-0 h-full w-full object-cover" src={heroVideo} autoPlay muted loop playsInline aria-hidden="true" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/55 to-ink/10" /><div className="relative mx-auto w-full max-w-[1440px] px-5 pb-10 lg:px-9 lg:pb-12"><p className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-sun">MTV Stuttgart 1843 e.V. präsentiert</p><h1 className="max-w-5xl break-words font-display text-[clamp(2.5rem,12vw,5rem)] font-extrabold uppercase leading-[0.84] tracking-[-0.075em] sm:text-[clamp(3.5rem,9.5vw,9.6rem)]">Unser neues<br /><span className="text-coral">Zuhause.</span></h1><div className="mt-10 flex flex-col justify-between gap-8 border-t border-white/30 pt-5 md:flex-row md:items-end"><p className="max-w-sm text-lg font-medium leading-snug md:text-xl">Mehr Community. Mehr Angebot.<br /><em className="font-display not-italic text-white">Mehr Möglichkeiten.</em></p><button onClick={() => scrollTo("neubau")} className="button-light">Jetzt entdecken <ArrowDownRight size={18} /></button></div></div><div className="announcement-badge w-[180px] max-w-[calc(100vw-2.5rem)] rounded-2xl bg-sun p-5 text-ink shadow-xl"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em]">Neueröffnung</p><p className="mt-1 font-display text-2xl font-bold">Januar 2027</p></div></section>
      <section id="neubau" className="relative px-5 py-24 lg:px-9 lg:py-36"><div className="grain absolute inset-0 opacity-50" /><div className="relative mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.85fr_1.15fr] lg:gap-24"><div><p className="eyebrow section-eyebrow text-base">01 / Der Neubau</p><h2 className="section-title mt-5">Ein Ort, der<br /><span>uns bewegt.</span></h2></div><div className="pt-2"><p className="max-w-2xl text-lg font-semibold leading-snug sm:text-2xl md:text-3xl">Am Kräherwald entsteht mehr als ein Gebäude. Ein Sportzentrum, das weit mehr als vier Wände bietet: ein lebendiger Treffpunkt für alle Generationen.</p><p className="mt-5 max-w-xl text-base leading-relaxed text-ink/60">Wir schaffen Räume für Bewegung, Begegnung und Weiterentwicklung. Für den ersten Purzelbaum genauso wie den persönlichen Bestmoment nach dem Training.</p><div className="mt-12 grid grid-cols-3 gap-2 border-t border-ink/20 pt-7 sm:gap-6"><div><strong className="block text-left font-display text-[22px] font-bold leading-none sm:text-[35px]">1</strong><span className="mt-4 block text-[10px] font-extrabold uppercase leading-tight tracking-wide sm:mt-5 sm:text-base">Starke<br />Gemeinschaft</span></div><div><strong className="block font-display text-[22px] font-bold leading-none sm:text-[35px]">100%</strong><span className="mt-4 block text-[10px] font-extrabold uppercase leading-tight tracking-wide sm:mt-5 sm:text-base">Barrierefrei</span></div><div><strong className="block text-left font-display text-[34px] font-bold leading-[22px] sm:text-[60px]">∞</strong><span className="mt-4 block text-[10px] font-extrabold uppercase leading-tight tracking-wide sm:mt-5 sm:text-base">Neue<br />Möglichkeiten</span></div></div></div></div></section>
      <section className="bg-cream-dark px-2 py-12 sm:px-4 lg:px-9 lg:py-20"><div className="mx-auto grid max-w-[1280px] gap-4 md:grid-cols-[1.2fr_0.8fr] md:grid-rows-[340px_280px]">{photos.map((photo, index) => <div key={photo} className={`group relative min-h-[220px] overflow-hidden sm:min-h-[280px] ${index === 0 ? "md:row-span-2" : ""}`}><img src={photo} alt="Gemeinsame Bewegung beim MTV Stuttgart" className={`absolute inset-0 h-full w-full transition duration-700 group-hover:scale-105 ${index === 1 ? "object-cover object-bottom" : index === 2 ? "object-cover object-top" : "object-cover"}`} /><div className={`absolute inset-0 ${index === 0 ? "bg-gradient-to-t from-ink/45 via-transparent to-transparent" : index === 1 ? "" : "bg-gradient-to-t from-ink/85 via-ink/10 to-transparent"}`} /><div className="absolute bottom-6 left-6 text-white"><p className="eyebrow text-sun text-base">{index === 0 ? "Inklusion" : index === 1 ? "Gemeinschaft" : "Weiterentwicklung"}</p><h3 className="mt-1 font-display text-lg font-bold uppercase text-white sm:text-2xl">{index === 0 ? "Jede:r gehört dazu." : index === 1 ? "Sport verbindet." : "Kinder bewegen Zukunft."}</h3></div></div>)}</div></section>
      <section id="angebot" className="bg-ink px-5 py-24 text-white lg:px-9 lg:py-32"><div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="eyebrow section-eyebrow text-sun text-base">02 / Unser Angebot</p><h2 className="section-title mt-5">Bewegung, die<br /><span>zu dir passt.</span></h2></div><div className="pointer-events-none absolute inset-x-0 top-[360px] z-20 flex -translate-y-1/2 justify-between"><button onClick={() => setActiveOffer((activeOffer - 1 + offerings.length) % offerings.length)} className="offer-carousel-control pointer-events-auto flex h-11 w-11 items-center justify-center rounded-full border border-sun bg-sun text-ink transition hover:border-white hover:bg-white hover:text-ink" aria-label="Vorheriges Angebot"><ArrowLeft size={18} /></button><button onClick={() => setActiveOffer((activeOffer + 1) % offerings.length)} className="offer-carousel-control pointer-events-auto flex h-11 w-11 items-center justify-center rounded-full border border-sun bg-sun text-ink transition hover:border-white hover:bg-white hover:text-ink" aria-label="Nächstes Angebot"><ArrowRight size={18} /></button></div></div><div className="mt-12 overflow-hidden"><div className="offer-track flex gap-4 transition-transform duration-500" style={{ transform: `translateX(calc(-${activeOffer} * var(--offer-step)))` }}>{offerings.map(([name, text, image], index) => <article key={name} className="group relative min-w-full overflow-hidden sm:min-w-[48%] xl:min-w-[31%]"><div className="aspect-[4/5] bg-wood"><img src={image} alt={`${name} beim MTV Stuttgart`} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/25 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-6 sm:p-8"><></><h3 className="mt-2 font-display text-3xl font-bold uppercase">{name}</h3><p className="mt-3 max-w-sm text-base leading-relaxed text-white/75">{text}</p></div></article>)}</div></div><div className="mt-7 flex items-center gap-2">{offerings.map(([name], index) => <button key={name} onClick={() => setActiveOffer(index)} aria-label={`${name} anzeigen`} className={`h-1.5 rounded-full transition-all ${index === activeOffer ? "w-10 bg-coral" : "w-5 bg-white/30"}`} />)} </div><a href={sportCoursesUrl} target="_blank" rel="noreferrer" className="offerings-link button-outline mt-6 lg:absolute lg:right-0 lg:top-[7rem] lg:mt-0">Alle Angebote</a></div></section>
      <section id="ausstattung" className="relative px-5 py-24 lg:px-9 lg:py-36"><div className="grain absolute inset-0 opacity-50" /><div className="relative mx-auto max-w-[1280px]"><p className="eyebrow section-eyebrow text-base">03 / Die Ausstattung</p><div className="mt-5 flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="section-title">Ein Haus voller<br /><span>Bewegung.</span></h2><p className="max-w-md text-base leading-relaxed text-ink/60">Fünf Ebenen, unzählige Möglichkeiten, 100% barrierefrei. Klicke auf eine Etage und entdecke, was dich erwartet.</p></div><div className="mt-16 grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div className="mx-auto flex w-full max-w-[430px] flex-col gap-1 border-x-8 border-t-8 border-ink/90 bg-ink/90 p-2 shadow-2xl overflow-x-hidden">{levels.map((level, index) => <div key={level[0]} className="flex w-full min-w-0 flex-col"><button onClick={() => setOpenLevel(index)} className={`floor flex items-center justify-between p-5 text-left transition ${openLevel === index ? "hidden lg:flex" : ""} ${openLevel === index ? `${level[5]} ${index === 0 ? "text-white" : ""}` : "bg-white/10 text-white hover:bg-white/20"}`}><span className={`font-display text-base font-bold sm:text-lg ${index === 4 ? "whitespace-nowrap" : ""}`}>{level[0]}</span><span className={`min-w-0 break-words ${[0, 3, 4].includes(index) ? "text-center" : "text-right"} text-xs font-bold uppercase leading-tight tracking-wider ${index === 0 ? "ml-[2px]" : ""}`}>{level[2]}</span><Plus size={18} className={openLevel === index ? "rotate-45 transition" : "transition"} /></button>{openLevel === index && <div className={`lg:hidden w-0 min-w-full max-w-full shrink overflow-hidden min-h-[350px] p-8 sm:p-12 ${level[5]} ${[0, 1, 2].includes(index) ? "text-white" : "text-ink"}`}><p className="text-xs font-bold uppercase tracking-[0.16em] opacity-70">{level[1]}</p><h3 className="mt-4 font-display text-2xl font-bold uppercase leading-tight sm:text-[32px]">{level[2]}</h3><p className="mt-6 max-w-lg leading-relaxed opacity-75">{level[3]}</p><ul className="mt-8 grid gap-3 border-t border-current/20 pt-6 sm:grid-cols-3">{level[4].map(item => <li key={item} className="text-sm font-bold">＋ {item}</li>)}</ul></div>}</div>)}</div><div className={`hidden lg:block h-full min-h-0 p-8 sm:p-12 ${current[5]} ${[0, 1, 2].includes(openLevel) ? "text-white" : "text-ink"}`}><p className="text-sm font-bold uppercase tracking-[0.16em] opacity-70">{current[1]}</p><h3 className="mt-4 font-display text-[32px] font-bold uppercase leading-none">{current[2]}</h3><p className="mt-6 max-w-lg leading-relaxed opacity-75">{current[3]}</p><ul className="mt-8 grid gap-3 border-t border-current/20 pt-6 sm:grid-cols-3">{current[4].map(item => <li key={item} className="text-sm font-bold">＋ {item}</li>)}</ul></div></div></div></section>
      <section className="relative bg-ink px-5 py-24 text-white lg:px-9 lg:py-32"><div className="mx-auto max-w-[1280px]"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><></><h2 className="section-title mt-5 text-white">Entdecke, was<br /><span>dich bewegt.</span></h2></div><p className="max-w-md text-base leading-relaxed text-white/60">Vier besondere Trainingswelten. Bewege den Cursor über eine Karte oder tippe sie an, um mehr zu erfahren.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{equipment.map(([title, subtitle, description, image]) => <div className="flip-card" key={title} tabIndex={0}><div className="flip-inner"><div className="flip-face flip-front" style={{ backgroundImage: `url(${image})` }}><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/45 to-ink/10" /><div className="relative mt-auto"><h3 className="mt-2 max-w-full break-all font-display text-base font-bold uppercase leading-tight sm:text-xl">{title}</h3><p className="mt-3 text-sm text-white/75">{subtitle}</p><></></div></div><div className="flip-face flip-back bg-coral text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-white/70">{title === "Lü-System" ? "L" : title}</p><h3 className="mt-4 font-display text-base font-bold uppercase leading-tight sm:text-2xl">{subtitle}</h3><p className="mt-6 text-sm leading-relaxed text-white/85">{description}</p><></></div></div></div>)}</div></div></section>
      <section id="kontakt" className="bg-coral px-5 py-24 text-white lg:px-9 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1fr_0.8fr] lg:gap-24"><div><p className="eyebrow section-eyebrow text-white/70 text-base">04 / Dabei sein</p><h2 className="section-title mt-5 text-white">Dein Platz<br />ist hier.</h2><p className="mt-8 max-w-md text-lg leading-[30px] text-white/80">Sichere dir jetzt deinen Platz in der MTV-Gemeinschaft und profitiere von vielfältigen Angeboten.</p><a href={mainSite} target="_blank" rel="noreferrer" className="button-light mt-8">Mitglied werden <ArrowRight size={17} /></a></div><form onSubmit={submit} className="newsletter-form min-w-0 w-full max-w-full overflow-hidden rounded-2xl bg-white p-7 text-ink sm:p-9">{sent ? <div className="flex min-h-[280px] flex-col justify-center"><Sparkles className="text-coral" /><h3 className="mt-5 font-display text-2xl font-bold sm:text-3xl">Danke für dein Interesse.</h3><p className="mt-3 text-ink/60">Wir melden uns bald bei dir.</p></div> : <><h3 className="font-display text-xl font-bold sm:text-2xl">Auf dem Laufenden bleiben</h3><p className="mt-2 text-lg leading-[30px] text-ink/60">Trag dich ein und erfahre zuerst, was sich am Kräherwald bewegt. Wir informieren dich über Eröffnung, Angebote und Probetrainings.</p><div className="mt-8 grid gap-4"><a href="https://www.mtv-stuttgart.de/aktuelles/newsletter" target="_blank" rel="noreferrer" className="newsletter-submit button-dark mt-2 w-full whitespace-normal text-center">Zum Newsletter anmelden <ArrowRight size={17} /></a></div></>}</form></div></section>
      <section id="standort" className="px-5 py-24 lg:px-9 lg:py-32"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1fr_1.1fr] lg:gap-24"><div><p className="eyebrow section-eyebrow text-base">05 / Standort</p><h2 className="section-title mt-5"><span className="location-heading-primary whitespace-nowrap">Wir sehen uns</span><br /><span>am Kräherwald.</span></h2><div className="mt-10 space-y-7">{[[MapPin, "MTV Stuttgart", "Am Kräherwald 188", "70193 Stuttgart"], [BusFront, "ÖPNV", "Mit Bus und Bahn bis zur Haltestelle", "Kräherwald."], [ParkingCircle, "Ankommen", "Fahrrad- und Parkmöglichkeiten", "direkt vor Ort."]].map(([Icon, title, line1, line2]) => <div className="flex gap-4" key={title as string}><Icon className="shrink-0 text-coral" /><div><p className="font-bold">{title as string}</p><p className="text-base text-ink/60">{line1 as string}<br />{line2 as string}</p></div></div>)}</div><a href="https://maps.google.com/?q=MTV+Stuttgart+Am+Kräherwald+188" target="_blank" rel="noreferrer" className="button-dark mt-10">Route planen <ArrowRight size={17} /></a></div><div className="relative min-h-[380px] overflow-hidden bg-wood p-8"><iframe title="MTV Stuttgart Standort auf Google Maps" src="https://www.google.com/maps?q=MTV+Stuttgart+Am+Kräherwald+188&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="absolute inset-0 z-10 h-full w-full border-0" /><div className="absolute inset-0 opacity-20" style={{ backgroundImage: "radial-gradient(#fff 1px, transparent 1px)", backgroundSize: "22px 22px" }} /><div className="relative flex h-full min-h-[300px] items-center justify-center border border-white/30"><div className="text-center text-white"><MapPin className="mx-auto mb-4" size={36} /><p className="max-w-full break-words font-display text-lg font-bold sm:text-2xl">Am Kräherwald 188</p><p className="mt-2 text-sm text-white/70">70193 Stuttgart</p></div></div></div></div></section>
      <section className="sponsor-strip bg-ink py-8 text-white" aria-label="Unsere Sponsoren"><div className="sponsor-marquee"><div className="sponsor-track">{[...sponsors, ...sponsors].map((sponsor, index) => <span className="sponsor-logo" key={`${sponsor}-${index}`}>{sponsor === "PSD Bank RheinNeckarSaar eG" ? <img src="https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F3def787e89754a2ea9a57bbe92c616ce?format=webp&width=800&height=1200" alt="PSD Bank RheinNeckarSaar eG" className="h-12 w-12 object-contain" /> : sponsor === "FinanzGefährte" ? <img src="https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fc0ee10192bfa4d278cccf24aef44e288?format=webp&width=800&height=1200" alt="FinanzGefährte" className="h-12 w-auto max-w-[240px] object-contain brightness-0 invert" /> : sponsor === "Friess + Merkle" ? <img src="https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fecee15712ba44c319e42386367e16b1f?format=webp&width=800&height=1200" alt="Friess + Merkle Elektrotechnik" className="h-12 w-auto max-w-[240px] object-contain brightness-0 invert" /> : sponsor === "BBBank eG" ? <img src="https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2Fe3e748efb08b4c439cfc24fd6b8b296e?format=webp&width=800&height=1200" alt="BBBank eG" className="h-12 w-auto max-w-[240px] object-contain brightness-0 invert" /> : sponsor}</span>)}</div></div><div className="mt-6 flex justify-center"><a href="https://www.paypal.com/donate/?hosted_button_id=CJHGKCM7KZD4J" target="_blank" rel="noreferrer" className="button-light">Werde jetzt Unterstützer:in <ArrowRight size={17} /></a></div></section>
      <section className="bg-cream-dark px-5 py-24 lg:px-9 lg:py-32"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-base font-[Space_Grotesk,sans-serif]">06 / FAQS</p><h2 className="section-title mt-5">Gut zu<br /><span>Wissen.</span></h2><div className="mt-12 border-t border-ink/20">{faqs.map(({ question, answer }, index) => <div key={question} className="border-b border-ink/20"><button onClick={() => setOpenFaq(openFaq === index ? -1 : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left font-display text-base font-bold sm:py-6 sm:text-lg"><span className="min-w-0 break-words">{question}</span><ChevronDown className={`shrink-0 text-coral transition ${openFaq === index ? "rotate-180" : ""}`} /></button>{openFaq === index && <p className="max-w-2xl pb-7 text-sm leading-relaxed text-ink/65">{answer}</p>}</div>)}</div></div></section>
    </main>
    <footer className="bg-ink px-5 py-12 text-white lg:px-9"><div className="mx-auto flex max-w-[1280px] flex-col justify-between gap-10 md:flex-row md:items-end"><div><Brand /><p className="mt-5 max-w-xs text-base leading-relaxed text-white/50">Mehr Community. Mehr Angebot. Mehr Möglichkeiten.</p></div><div className="flex gap-4"><a href="https://www.instagram.com/mtvstuttgart1843ev/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram /></a><a href="https://www.facebook.com/mtv.stuttgart/" target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook /></a><a href="https://fr.linkedin.com/company/mtv-stuttgart-1843-e-v" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href="https://www.youtube.com/@mtvstuttgart1843eV" target="_blank" rel="noreferrer" aria-label="YouTube"><Youtube /></a><a href="https://open.spotify.com/show/033KSPWWRBOjlTzB0Q6VSy?si=8fe8a1aa48a54d5f" target="_blank" rel="noreferrer" aria-label="Spotify"><img src="https://cdn.builder.io/api/v1/image/assets%2Fddb6ea6a9b7b4321af836c3cfcfa84c7%2F0f6789df4cec497fadedb28408927f24?format=webp&width=800&height=1200" alt="Spotify" className="h-8 w-8 object-contain mix-blend-screen" /></a><a href="https://podcasts.apple.com/de/podcast/westfunk/id6788110761" target="_blank" rel="noreferrer" aria-label="Apple Podcasts"><Podcast /></a><a href="https://link.deezer.com/s/34dGXgmClW9G1zwLjIk7Q" target="_blank" rel="noreferrer" aria-label="Deezer"><Music2 /></a></div></div><div className="mx-auto mt-12 flex max-w-[1280px] flex-col justify-between gap-4 border-t border-white/15 pt-5 text-xs text-white/40 md:flex-row"><span className="text-sm">© 2026 MTV Stuttgart 1843 e.V.</span><span><a href="https://www.mtv-stuttgart.de/impressum" target="_blank" rel="noreferrer" className="text-sm transition-colors hover:text-white">Impressum</a> · <a href="https://www.mtv-stuttgart.de/datenschutz" target="_blank" rel="noreferrer" className="text-sm transition-colors hover:text-white">Datenschutz</a> · <a href="https://www.mtv-stuttgart.de/service/kontakt" target="_blank" rel="noreferrer" className="text-sm transition-colors hover:text-white">Kontakt</a></span></div></footer>
  </div>;
}
